#!/bin/sh

MM_RESTART=false
OFONO_RESTART=false

if systemctl is-active --quiet ModemManager; then
    MM_RESTART=true
    systemctl stop ModemManager
fi

if systemctl is-active --quiet ofono; then
    OFONO_RESTART=true
    systemctl stop ofono
fi

# Remove NM connection data
# this should preferrably be updated by ofono2mm instead if ofono's APN is different from existing connection
if [ -d /etc/NetworkManager/system-connections/ ]; then
    grep -rilZ "type=gsm" /etc/NetworkManager/system-connections/ | xargs -0 -r rm -f
fi

# Get rid of the context cache
if [ -d /var/lib/ofono ]; then
    find /var/lib/ofono -name "gprs" -exec rm -f {} \;
fi

if [ "$OFONO_RESTART" = true ]; then
    systemctl start ofono
fi

if [ "$MM_RESTART" = true ]; then
    systemctl start ModemManager
fi
